version: "3.2"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - deephub-net

  keycloak:
    image: docker.io/bitnami/keycloak:23
    depends_on:
      - postgresql
    ports:
      # make keycloak reachable from host for using the administration console web interface
      - "80:8080"
    networks:
      - deephub-net

  deephub:
    image: flowcate/deephub:2.5.0
    container_name: deephub-2.5.0-https-auth
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    environment:
      - DEEPHUB_PORT=7081
      - DEEPHUB_HOST=0.0.0.0
      - DEEPHUB_CORS=true
      - DEEPHUB_REQUIRE_AUTHORIZATION=true
      # work with "direct" connection via the "deephub-net" docker network
      - DEEPHUB_OPENID_CONFIG_URL=http://keycloak:8080/realms/omlox/.well-known/openid-configuration
      - DEEPHUB_OPENID_CLIENT_NAME=deephub-test-client
      - DEEPHUB_LICENSE_KEY=cf578926-8acb-4b8c-986c-d813ff435b1b
      - SQLITE_TMPDIR=/data
    depends_on:
      - keycloak
    ports:
      - "7081"
    volumes:
      - "./hub-data/:/data"
    networks:
      - deephub-net

  deephub-admin-ui:
    image: flowcate/deephub-ui:2.5.0-nginx-1.26.0
    container_name: deephub-admin-ui-2.5.0-https-auth
    tty: true
    stdin_open: true
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - "./hub-web/:/tmp/run"
      - "./hub-web/nginx/log/:/var/log/nginx"
      - "./hub-web/nginx/cache/:/var/cache/nginx"
      - "./hub-web/nginx/webapp/:/webapp"
    environment:
      - DEEPHUB_ROOT_URL=/deephub
      - NGINX_BASE_HREF=/deephub-admin-ui/
      - DEEPHUB_MAP_UPDATES_PER_SECOND=10
      # "localhost" has to be used here because these variables are used within the client browser and there, keycloak and UI can be reached
      # at "localhost" and not as the "keycloak" name valid within the docker network.
      - DEEPHUB_AUTH_ISSUER=http://localhost/realms/omlox
      - DEEPHUB_AUTH_REDIRECT_URI=https://localhost/deephub-admin-ui/
      - DEEPHUB_AUTH_CLIENT_ID=deephub-admin-ui-test-client
    networks:
      - deephub-net

  deephub-kiosk-ui:
    image: flowcate/deephub-ui:2.5.0-nginx-1.26.0
    container_name: deephub-kiosk-ui-2.5.0-https-auth
    tty: true
    stdin_open: true
    read_only: false
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - "./hub-web/:/tmp/run"
      - "./hub-web/nginx/log/:/var/log/nginx"
      - "./hub-web/nginx/cache/:/var/cache/nginx"
      - "./hub-web/nginx/conf.d/:/etc/nginx/conf.d"
    environment:
      - NGINX_BASE_HREF=/deephub-kiosk-ui/
      - DEEPHUB_ROOT_URL=/deephub
      - DEEPHUB_AUTH_ISSUER=http://localhost/realms/omlox
      - DEEPHUB_AUTH_REDIRECT_URI=https://localhost/deephub-kiosk-ui/
      - DEEPHUB_AUTH_CLIENT_ID=deephub-kiosk-ui-test-client
    networks:
      - deephub-net

  deephub-apache:
    image: httpd:alpine
    container_name: deephub-apache-2.5.0-https-auth
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub-admin-ui
      - deephub-kiosk-ui
    ports:
      - "443:443"
    volumes:
      - "./apache/conf:/usr/local/apache2/conf"
      - "./apache/htdocs:/usr/local/apache2/htdocs"
      - "./apache/logs:/usr/local/apache2/logs"
    networks:
      - deephub-net

volumes:
  postgresql_data:
    driver: local

networks:
  deephub-net:
